### ISSUE TITLE
Problem for executing .jar

### ISSUE THREAD

**Issue by akumareutre** [rabume/cs2-dma-radar#1]
hi man thanks for providing the .jar unfortunately I have this error do you know how to fix this?

`C:\Users\PC\Desktop\cs2-dma-radar\release>java -jar CS2DMA-1.0.jar
[+] Read offsets.json file
[+] dwLocalPlayerPawn: 25648200
[+] dwEntityList: 24676568
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: vmm.VmmException: Vmm Init: failed in native code.
        at vmm.internal.VmmImpl.<init>(VmmImpl.java:57)
        at vmm.internal.VmmImpl.Initialize(VmmImpl.java:76)
        at vmm.IVmm.initializeVmm(IVmm.java:32)
        at cs2.dma.tuil.GameDataManager.initializeVmm(GameDataManager.java:66)
        at cs2.dma.main.Application.main(Application.java:17)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 5 more`

**Comment by rabume** [comment]
Hey :wave: 
I'm sorry for the late answer. I also had this error sometimes. I had to restart the target & attacker machine.
Do you still experience this error?

My guess was, that my card was overheating, because of the not ideal approach with requesting a single endpoint all 100ms.
Do you own a card with any cooling elements?
