### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by supertrio17** [rabume/cs2-dma-radar#15]
Hey, I get this error and cant start the program:

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: vmm.VmmException: Vmm Init: failed in native code.
        at vmm.internal.VmmImpl.<init>(VmmImpl.java:57)
        at vmm.internal.VmmImpl.Initialize(VmmImpl.java:76)
        at vmm.IVmm.initializeVmm(IVmm.java:32)
        at cs2.dma.tuil.GameDataManager.initializeVmm(GameDataManager.java:66)
        at cs2.dma.main.Application.main(Application.java:17)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 5 more`

**Comment by Suspectxyzz** [comment]
[+] Read offsets.json file
[+] dwLocalPlayerPawn: 23891800
[+] dwEntityList: 24910160
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:95)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)
Caused by: vmm.VmmException: Vmm Init: failed in native code.
        at vmm.internal.VmmImpl.<init>(VmmImpl.java:57)
        at vmm.internal.VmmImpl.Initialize(VmmImpl.java:76)
        at vmm.IVmm.initializeVmm(IVmm.java:32)
        at cs2.dma.tuil.GameDataManager.initializeVmm(GameDataManager.java:66)
        at cs2.dma.main.Application.main(Application.java:17)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        ... 5 more

**Comment by huntergregal** [comment]
Are you both trying to run this on linux?

I had the same issue and after a lot of debugging I disovered the issued was that `leechcore_ft601_driver_linux.so` must be in `vmm/` alongside of the `.so`

I also added the path fix to `app/src/main/java/cs2/dma/tuil/GameDataManager.java`

```
    public boolean initializeVmm() {
        String OS = System.getProperty("os.name").toLowerCase();
        if (OS.contains("win")) {
            this.vmm = IVmm.initializeVmm(System.getProperty("user.dir") + "\\vmm", argvMemProcFS);
        } else { // assume linux
            this.vmm = IVmm.initializeVmm(System.getProperty("user.dir") + "/vmm", argvMemProcFS);
        }
        vmm.setConfig(IVmm.VMMDLL_OPT_REFRESH_FREQ_FAST, 1);
        return vmm.isValid();
    }

```

**Comment by rabume** [comment]
Hey, I don't think they've attempted to run this on Linux, but you're right; this information should be documented.

**Comment by huntergregal** [comment]
I have it running on a raspi 4 and routing over an ssh tunnel to a remote server. I also changed it to only listen on localhost. Some anticheats (not VAC but better safe then sorry) will scan the network for radars

**Comment by huntergregal** [comment]
@Suspectxyzz I'd love to test out your python based radar. But webserver support is a must. i think you may need to ditch pygame and get something up with flask or node.

@rabume i have some issues with map selection and layout. I'll see about contributing if i come up with fixes. HP tracker would be huge too - the offset support is there for pawnHealth.

**Comment by rabume** [comment]
It's merely a fork. I would approach many aspects differently. I'm recreating the radar in Rust with WebSockets.

**Comment by rabume** [comment]
@huntergregal 

When I tried sharing the radar, it was quite buggy, and my card overheated. 😅 That's why I think the websocket approach is significantly better.

**Comment by huntergregal** [comment]
> @huntergregal
> 
> When I tried sharing the radar, it was quite buggy, and my card overheated. 😅 That's why I think the websocket approach is significantly better.

rust would be dope. 

I will probably hack this java backend onto https://github.com/clauadv/cs2_webradar frontend
